### ISSUE TITLE
Various small things

### ISSUE THREAD

**Issue by robinwhittleton** [dajare/william-makepeace-thackeray_the-history-of-henry-esmond#1]
general
- hgroup semantics have changed. See https://standardebooks.org/manual/1.7.2/single-page#7.2.6
- core.css needs an update to the latest version

content.opf
- replace `se:role` with `role`
- You’ve got Thackeray down as `wpr`, but that seems to have been written by a “Rachel Esmond Warrington”. A bunch of the endnotes are signed R. or R. E. W., so I guess she should also have role `ann`?

book-1
- I wonder if this would benefit from `prologue` semantics?

chapter-1-5
- Commit f0261ff7b7d3bdde91a7408c4d282ce8a551d73b looks wrong. It’s been a while since I studied French, but pensait seems the correct conjugation here?

chapter-1-9 / chapter-1-12
- non-breaking hyphen needed for `G-d`

chapter-2-11
- The latin blockquote is missing italicisation styles in local.css. See https://standardebooks.org/manual/1.7.2/single-page#8.2.9.6

chapter-2-15
- modernize-spelling suggests villanies -> villainies which seems reasonable

chapter-3-3
- “I spell it with a Y.” <- needs grapheme semantics: https://standardebooks.org/manual/1.7.2/single-page#8.2.8.2
- I couldn’t actually get it to break, but whenever I see a float I want to see a clear on the following element that I definitely don’t want to overlap. I’d personally add clear:right to chapter 3 epigraphs.

endnotes:
- Lint flags a problem with the Greek in note-3. Bump standardebooks to the latest version and rerun it? Looks like it’s just changing the koronis characters to apostophes
- Notes 4 and 13 are signed H. E., so need a `z3998:fiction` epub type?

**Comment by dajare** [comment]
Thanks, @robinwhittleton! I've made all the changes, except the three marked **N.b.**, below (= `content.opf` + `c1-5` + `endnotes`(2)). You can set me straight on those. :)

---

general | `core.css` and all `hgroup`s updated

content.opf

- `se:role` changed to `role`
- **N.b.** "Thackeray down as `wpr`" : “Rachel Esmond Warrington” is a fictional character, writing of fictional things (preface includes `z3998:fiction` semantic). Doesn't this make Thackeray `wpr`? See also "endnotes", below.

book-1

- `prologue` semantics added, on model of * The Narrative of Arthur Gordon Pym...*, as per SEMoS § 3.2.1. Hope I've done that correctly.

c1-5

- **N.b.** *pensait* or *pensoit* - I went with latter because that's the way it appears in (1) [Oxford World Classic](https://archive.org/details/historyofhenrye000thac/page/55/mode/1up?view=theater) and (2) ["Critical" OUP edition (1915)](https://babel.hathitrust.org/cgi/pt?id=chi.15169089&view=1up&seq=95) (had super helpful notes). PNGs pasted below; of course I'm happy to revert if that's preferable! (Btw, the IA link needs a "sign-in" to "borrow"; the HathiTrust link I needed a USA-based VPN to view.)

(1)
![Selection_080](https://github.com/dajare/william-makepeace-thackeray_the-history-of-henry-esmond/assets/40625/2f32a130-ff10-4b2a-9240-08976777fa72)

(2)
![pensoit-p55](https://github.com/dajare/william-makepeace-thackeray_the-history-of-henry-esmond/assets/40625/d662ab9a-5f3b-4b32-a3fd-73d8db58a214)

cc1-9, 1-12 | `G-d` hyphens changed to `u+2011`

c2-11 + local.css | blockquote lang italics rule added to `local.css`

c2-15 | `villanies` > `villainies` done \[Editorial\]

c3-3 | "spell it with a Y." > semantics added; NOT added in postscript two paragraphs later, "the reason Y."   
c3-3 | `clear: right` rule added for bespoke c3-3 in `local.css` (**hope** I put it in the correct place!)

endnotes (1) | note-3, fixed 2x the bad `U+1FBD` (koronis) character for `U+2019` (rsquo) (I see I picked up the koronis from the [Perseus encoding](https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.01.0135)—I think so, anyway, fwiw.)  
endnotes (2) | **N.b.** As with the "author" of the prologue, the endnotes (see "fictional" semantic on `body` tag) by the fictional writer of the memoir, or its fictional annotaters. Like the "Preface", don't these all get assigned to Thackeray himself?

**Comment by robinwhittleton** [comment]
Oops, missed that the preface was marked as fiction So `wpr` and `ann` for Thackeray make total sense. The `z3998:fiction` for all the endnotes _could_ be correct, but only if all the endnotes are fictional. What do you think?

For the `float`/`clear`, it would need to be the following element that had `clear` applied. So remove the one you’ve currently added, and add the following rule after:

```
#chapter-3-3 blockquote blockquote{
	clear: right;
}
```

On the `pensait`/`pensoit` question, I‘ll ask on the mailing list. My French is definitely not good enough to make a call one way or the other.

Rest looks great, thanks!

**Comment by dajare** [comment]
- "`z3998:fiction` for all the endnotes" | that was my working assumption. The novel presents as Henry Esmond's "memoir", and my sense is that all the notes serve that (fictive) purpose. The only note one *might* say is not fictional is that n. 3 (the quote from Homer's *Odyssey*), but that, too, simply serves the narrative. None of the others are "factual", so I take them all as part of the "published (fictional) memoir". Does that help?

- I dropped that `float` commit, and added the rule you kindly supplied at the point you directed in a [new commit, `ca16260`](https://github.com/dajare/william-makepeace-thackeray_the-history-of-henry-esmond/commit/ca16270cd8f01f3c0a6a6640b196ac49f8345afc). Hope that's got it!

- On the `pensait/pensoit` question : we'll see what turns up on the mailing list. Hopefully one of the francophone participants will spot it soon!

**Comment by dajare** [comment]
Hi @robinwhittleton  - I did what I probably ought to have done earlier, and checked a bevy (well, five; see below) more modern and differently typeset editions of *Esmond*. All of them have "*pensait*", and I repent of making the \[Editorial\] change to "*pensoit*". I don't know what else might have changed in c1-5, nor quite how dropping that commit would work, so I'll make a new commit (also /[Editorial/]) reverting that.

It wasn't all in vain, though. I did notice while doing this that there is a typo at [the end of line 56](https://github.com/dajare/william-makepeace-thackeray_the-history-of-henry-esmond/blob/ca16270cd8f01f3c0a6a6640b196ac49f8345afc/src/epub/text/chapter-1-5.xhtml#L56) (two paragraphs up from the *pensait* paragraph): it reads `looked seared for a moment`, where it should read `scared`. That's a typo in the PG transcription. I'll fix that, too. After that, if you're content, it ought to be ready for Alex. I hope. :)

---

These all have "*pensait*":
- [The history of Henry Esmond : Thackeray, William Makepeace](https://archive.org/details/historyofhenrye00thac/page/90/mode/2up?q=midday "The history of Henry Esmond : Thackeray, William Makepeace")
- [The history of Henry Esmond, Esq. : a colonel in the service of Her Majesty Queen Anne written by himself : Thackeray, William Makepeace, 1811-1863](https://archive.org/details/historyofhenr00thac/page/58/mode/2up?q=whitefoot "The history of Henry Esmond, Esq. : a colonel in the service of Her Majesty Queen Anne written by himself : Thackeray, William Makepeace, 1811-1863")
- [The History Of Henry Esmond : William Makepeace Thackeray](https://archive.org/details/historyofhenryes0000will_z9z3/page/76/mode/2up?q=whitefoot "The History Of Henry Esmond : William Makepeace Thackeray")
- [The history of Henry Esmond : Thackeray, William Makepeace, 1811-1863](https://archive.org/details/historyofhenryestha00thac/page/42/mode/2up?q=scared "The history of Henry Esmond : Thackeray, William Makepeace, 1811-1863")
- [Henry Esmond. Introduction and notes by Gilbert Phelps : Thackeray, William Makepeace, 1811-1863](https://archive.org/details/henryesmondintro0000thac/page/48/mode/2up?q=pensait "Henry Esmond. Introduction and notes by Gilbert Phelps : Thackeray, William Makepeace, 1811-1863")

**Comment by robinwhittleton** [comment]
OK, great! I’m mostly glad my school French was enough to trigger a hmm.

When you’ve updated `seared` to `scared` I’ll let Alex know we’re ready.

**Comment by dajare** [comment]
Okay - all done, Robin. Hope that looks in order!
